#!/bin/bash -e
bwrap --dev-bind / / \
      --bind /opt/apps/com.qq.weixin/uos-release /etc/os-release \
      --bind /opt/apps/com.qq.weixin/uos-lsb /etc/lsb-release \
      /opt/apps/com.qq.weixin/files/wechat
